tNode(tail, 1, 3);
    print(tail);
    insertNode(tail, 1, 2);
    print(tail);
    insertNode(tail, 2, 5);
    print(tail);
    insertNode(tail, 2, 4);
    print(tail);
    insertNode(tail, 2, 3);
    print(tail);